# ===============================
# = Hibernate datasource
# ===============================
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_test?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 251099

  # ===============================
  # = JPA configurations
  # ===============================s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
